# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "marimo",
#     "pydantic-ai",
#     "pydantic-settings",
#     "aiosqlite",
#     "python-dotenv",
#     "anywidget==0.11.0",
# ]
# ///
"""
LLMWiki Read App
----------------
Read and navigate wiki pages generated by the ingest pipeline.
Chat with your knowledge base via a PydanticAI agent backed by FTS5 search.

Pages are read-only here — all content comes from the ingest pipeline.
"""

import marimo

__generated_with = "0.23.8"
app = marimo.App(width="full", layout_file="layouts/read_app.grid.json")

with app.setup:
    """Initialize environment, paths, and wiki agent."""
    import sys
    import marimo as mo
    import os
    import re
    import logging
    from pathlib import Path
    from dotenv import load_dotenv

    load_dotenv()

    debug_enabled = os.environ.get("DEBUG") or os.environ.get("WIKI_DEBUG")
    log_level = logging.DEBUG if debug_enabled else logging.WARNING
    logging.basicConfig(level=log_level, format="[%(levelname)s] %(name)s: %(message)s")
    logger = logging.getLogger("wiki_app")

    WIKI_PATH = Path(os.environ["WIKI_PATH"])

    _project_root = Path(__file__).parent.parent
    _api_new = str(_project_root / "api_new")
    if _api_new not in sys.path:
        sys.path.insert(0, _api_new)
    _marimo = str(_project_root / "marimo")
    if _marimo not in sys.path:
        sys.path.insert(0, _marimo)
    sys.modules.pop("config", None)

    from config import settings
    from domain.chat.agent import create_agent
    from domain.chat.config import load_config
    from widgets.delete_confirm import DeleteConfirmWidget

    wiki_db_path = str(WIKI_PATH / ".llmwiki" / "index.db")
    wiki_chat_config = load_config(WIKI_PATH)
    wiki_agent = create_agent(
        settings.LLM_BASE_URL, settings.LLM_API_KEY, settings.LLM_MODEL,
        system_prompt=wiki_chat_config.system_prompt,
    )


@app.cell
def styles():
    """Custom CSS: tighten prose spacing."""
    mo.Html("""<style>
    .prose span.paragraph { display: block; margin-top: 0.2em; margin-bottom: 0.2em; }
    .prose h1, .prose h2, .prose h3 { margin-top: 0.6em; margin-bottom: 0.2em; }
    .prose li { margin-top: 0.1em; margin-bottom: 0.1em; }
    </style>""")
    return


@app.cell
def wiki_helpers():
    """File helpers: scan and read wiki pages."""
    wiki_dir = WIKI_PATH / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)

    def scan_pages():
        return sorted(
            str(p.relative_to(wiki_dir).with_suffix(""))
            for p in wiki_dir.rglob("*.md")
        )

    def read_page(rel_path):
        path = wiki_dir / f"{rel_path}.md"
        return path.read_text(encoding="utf-8") if path.exists() else ""

    return read_page, scan_pages


@app.cell
def page_state(scan_pages):
    """Reactive state: page list and current selection."""
    page_list, set_page_list = mo.state(scan_pages(), allow_self_loops=True)
    initial_pages = page_list()
    selected_page, set_selected_page = mo.state(
        initial_pages[0] if initial_pages else None
    )
    delete_trigger, set_delete_trigger = mo.state(None)
    last_delete_event, set_last_delete_event = mo.state(0)
    return (
        delete_trigger,
        last_delete_event,
        page_list,
        selected_page,
        set_delete_trigger,
        set_last_delete_event,
        set_page_list,
        set_selected_page,
    )


@app.cell
def left_panel(page_list, scan_pages, set_page_list, set_selected_page):
    """Navigation sidebar — column 0."""
    pages = page_list()

    def _page_row(p):
        parts = p.rsplit("/", 1)
        directory = parts[0] if len(parts) > 1 else ""
        slug = parts[-1]
        title = slug.replace("-", " ").replace("_", " ").title()
        return {"Title": title, "Directory": directory, "Slug": slug}

    _table_data = [_page_row(p) for p in pages] if pages else [{"Title": "(no pages)", "Directory": "", "Slug": ""}]

    def _on_select(rows):
        if not rows:
            return
        r = rows[0]
        path = f"{r['Directory']}/{r['Slug']}" if r["Directory"] else r["Slug"]
        set_selected_page(path)

    page_selector = mo.ui.table(
        _table_data,
        selection="single",
        on_change=_on_select,
    )
    refresh_btn = mo.ui.button(
        label="⟳ Refresh",
        on_click=lambda _: set_page_list(scan_pages()),
    )
    mo.vstack([page_selector, refresh_btn], gap=2)
    return


@app.cell
def delete_widget_cell(selected_page, set_last_delete_event):
    """Delete confirm widget — self-contained button + inline confirmation panel."""
    delete_page = selected_page()
    set_last_delete_event(0)
    delete_widget = mo.ui.anywidget(
        DeleteConfirmWidget(
            label=delete_page or "",
            disabled=not delete_page,
        )
    )
    delete_widget
    return delete_page, delete_widget


@app.cell
def delete_event_cell(
    delete_page,
    delete_widget,
    last_delete_event,
    set_delete_trigger,
    set_last_delete_event,
):
    """Fires delete_trigger when the widget reports a confirmed deletion."""
    import time as _time

    _event_id = delete_widget.event_id
    if _event_id > last_delete_event() and delete_page:
        set_last_delete_event(_event_id)
        set_delete_trigger((delete_page, _time.time()))
    return


@app.cell
def delete_runner(
    delete_trigger,
    scan_pages,
    set_page_list,
    set_selected_page,
):
    """Executes wiki page deletion when delete_trigger fires."""
    from domain.tools.wiki_fs import delete_page as _delete_page

    mo.stop(delete_trigger() is None)
    page_stem, _ = delete_trigger()

    parts = page_stem.rsplit("/", 1)
    dir_path = f"/wiki/{parts[0]}/" if len(parts) > 1 else "/wiki/"
    slug = parts[-1]

    try:
        _delete_page(wiki_db_path, WIKI_PATH, dir_path, slug)
        set_page_list(scan_pages())
        set_selected_page(None)
        mo.callout(mo.md(f"✅ Deleted `{page_stem}`"), kind="success")
    except Exception as exc:
        mo.callout(mo.md(f"❌ Deletion failed: {exc}"), kind="danger")
    return


@app.cell
def current_page(read_page, selected_page):
    """Load the selected page from disk."""
    selected_stem = selected_page() if selected_page() else ""
    current_content = read_page(selected_stem) if selected_stem else ""
    return current_content, selected_stem


@app.cell
def page_links_nav(current_content, page_list, set_selected_page):
    """Navigation buttons for internal wiki links found on the current page."""
    raw_links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', current_content or "")
    seen = set()
    valid = {}
    for _label, stem in raw_links:
        page = stem.removesuffix(".md")
        if page.startswith("http") or page.startswith("mailto"):
            continue
        if page in page_list() and page not in seen:
            seen.add(page)
            valid[page.replace("-", " ").title()] = page

    def _make_handler(page):
        def _go(_v):
            set_selected_page(page)
        return _go

    buttons = [
        mo.ui.button(label=title, on_click=_make_handler(page), kind="neutral")
        for title, page in valid.items()
    ]
    nav_widget = mo.hstack(buttons, wrap=True, gap=1) if buttons else mo.Html("")
    return (nav_widget,)


@app.cell(column=1)
def middle_panel(current_content, nav_widget, selected_stem):
    """Content viewer — column 1."""
    _title = selected_stem.rsplit("/", 1)[-1].replace("-", " ").title() if selected_stem else "No page selected"
    _header = mo.md(f"## {_title}")

    _text = (
        re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', current_content)
        if current_content
        else "*Select a page from the left panel.*"
    )
    _scroll = mo.Html(
        f'<div style="height:70vh; overflow-y:auto; padding-right:8px;">'
        f'{mo.md(_text).text}'
        f'</div>'
    )
    mo.vstack([_header, mo.vstack([_scroll, nav_widget], gap=2)], gap=2)
    return


@app.cell(column=2)
def chat_panel():
    """AI chat assistant with FTS5 retrieval — column 2."""
    from pydantic_ai.messages import ModelRequest, UserPromptPart, ModelResponse, TextPart

    last_response, set_last_response = mo.state("")

    async def respond(messages, config):
        history = []
        for msg in messages[:-1]:
            if msg.role == "user":
                history.append(ModelRequest(parts=[UserPromptPart(content=msg.content)]))
            elif msg.role == "assistant":
                history.append(ModelResponse(parts=[TextPart(content=msg.content)]))

        full_text = ""
        async with wiki_agent.run_stream(
            messages[-1].content, deps=wiki_db_path, message_history=history
        ) as result:
            async for chunk in result.stream_text(delta=True):
                full_text += chunk
                yield chunk

        set_last_response(full_text)

    chat = mo.ui.chat(
        respond,
        prompts=wiki_chat_config.suggested_prompts,
        max_height=600,
    )
    mo.vstack([mo.md("### Chat with your Wiki"), chat], gap=2)
    return (last_response,)


@app.cell
def save_form(last_response):
    """Save-to-wiki form — value persists after submission (unlike a button)."""
    _title = mo.ui.text(label="Title", placeholder="Page title...")
    _category = mo.ui.dropdown(
        {"Concept": "concept", "Summary": "summary"},
        label="Category",
        value="Concept",
    )

    def _validate(v):
        if not last_response():
            return "Chat with the assistant first."
        if not (v.get("title") or "").strip():
            return "Title cannot be empty."
        return None

    form = (
        mo.md("### Save last response to wiki\n\n{title}\n\n{category}")
        .batch(title=_title, category=_category)
        .form(submit_button_label="💾 Save to wiki", validate=_validate)
    )
    form
    return (form,)


@app.cell
def save_action(form, last_response):
    """Show result after form submission — re-runs when form.value changes."""
    from openai import OpenAI
    from domain.chat.wiki_tools import save_to_wiki

    _llm_client = OpenAI(base_url=settings.LLM_BASE_URL, api_key=settings.LLM_API_KEY)

    def _run():
        if form.value is None:
            return mo.md("")
        title = (form.value.get("title") or "").strip()
        category = form.value.get("category", "concept")
        try:
            msg = save_to_wiki(
                wiki_db_path, WIKI_PATH, title, last_response(), category,
                client=_llm_client, model=settings.LLM_MODEL,
            )
            return mo.callout(mo.md(f"✅ {msg}"), kind="success")
        except Exception as exc:
            return mo.callout(mo.md(f"❌ Save failed: {exc}"), kind="danger")

    out = _run()
    out
    return


if __name__ == "__main__":
    app.run()
