"""Fake OpenAI client for testing LLM-dependent code without API calls."""

_DEFAULT_CONTENT = """\
# Fake Wiki Page

## Summary
This is a fake wiki page generated by FakeLLMClient for testing purposes.
The document covers fictional topics useful for asserting pipeline behaviour.

## Key Topics
- Fake Topic 1
- Fake Topic 2

## Key Entities
- Entity A
- Entity B

## Important Data & Figures
- 42 items processed

## Source Information
- **File:** test.pdf
- **Type:** pdf
- **Pages:** 1
- **Ingested:** 2026-01-01
- **Parser:** fake
"""


class _FakeMessage:
    def __init__(self, content: str) -> None:
        self.content = content


class _FakeChoice:
    def __init__(self, content: str) -> None:
        self.message = _FakeMessage(content)


class _FakeResponse:
    def __init__(self, content: str) -> None:
        self.choices = [_FakeChoice(content)]


class _FakeCompletions:
    def __init__(self, client: "FakeLLMClient") -> None:
        self._client = client

    def create(self, model: str, messages: list, **kwargs) -> _FakeResponse:
        self._client.calls.append({"model": model, "messages": messages, **kwargs})
        return _FakeResponse(self._client.next_response())


class _FakeChat:
    def __init__(self, client: "FakeLLMClient") -> None:
        self.completions = _FakeCompletions(client)


class FakeLLMClient:
    """Fake for openai.OpenAI. Implements client.chat.completions.create() interface.

    Single response mode: set ``response_content`` — every call returns it.
    Sequential mode: set ``responses`` (list of strings) — calls consume the list
    in order, cycling back to the last item when exhausted.
    Inspect ``calls`` after a call to assert what was sent.
    """

    def __init__(
        self,
        response_content: str = _DEFAULT_CONTENT,
        responses: list[str] | None = None,
    ) -> None:
        self.response_content = response_content
        self.responses = responses
        self._call_index: int = 0
        self.calls: list[dict] = []
        self.chat = _FakeChat(self)

    def next_response(self) -> str:
        if self.responses:
            idx = min(self._call_index, len(self.responses) - 1)
            self._call_index += 1
            return self.responses[idx]
        return self.response_content
